#!/bin/bash
# 添加一个用户，并且记录加入的是谁
# 用法： adduser username 张三
sudo useradd $1 -s /bin/bash -m 
echo $1 $2 $(date) >> ~/.userscripts/.users
sudo cp ~/.userscripts/.users /root/.config
(echo 'password'
sleep 1
echo 'password')|sudo passwd $1 
echo "使用passwd改密码，初始密码为password"
sudo edquota -p charlesxu $1
sudo xfs_quota -x -c "limit -u bsoft=50G bhard=100G $1" /home
