#!/usr/bin/fish
# 检查硬盘配额，需要配置好配额之后阅读明白本脚本再使用

cd /home

echo 'quota for /data'
echo 'username' (quota charlesxu|head -2|tail -1)>/tmp/quota;for i in (ls);echo $i (quota $i|tail -2|head -1);end > /tmp/quota
cat /tmp/quota |awk '{printf "%-12s|%15s|%15s|%9s|%9s|\n", $1, $3, $4, $5, $6}'
rm /tmp/quota


echo '\n\n\n'
xfs_quota -x -c "report -ubih" /home
